### ISSUE TITLE
Webhooks not registering correctly

### ISSUE THREAD

**Issue by tobeee** [kevinhughes27/shopify-sinatra-app#11]
I created an extra webhook to double check everything was working correctly. However, it never seems to get called. I'm currently using the webhook by manually setting up a notification inside the main Shopify notifications page but it's obviously not ideal. 

Code sample pasted below. Any ideas?

#route 
```
post '/order.json' do
    puts "Hook hit"
    webhook_session do |order|
    end
end
```

#def install
```
...
  order_webhook = ShopifyAPI::Webhook.new({
              topic: "orders/create",
              address: "#{base_url}/order.json",
              format: "json"
            })
      order_webhook.save
..
```

**Comment by kevinhughes27** [comment]
Yeah webhooks created in the admin are not the same as those created by the app. The webhook_session block will filter invalid webhooks and then one you created in the admin will not be signed properly for the app so it will be invalid. 

Do you get the other webhook you created from install? 

I am also planning to update the `install` method. Rather than calling it install its really an `after_auth` callback and this callback can run anytime someone logs in. This is easier than trying to keep track of the installed state. The new install will need to be idempotent (i.e. running it twice is the same as running it once). Have a look at shopify_app and the new webhooks manager to see what it will be like.

**Comment by tobeee** [comment]
Nope no web hooks get hit at all when installed through the gem itself.

I'll have a look at the Rails app and see if there are any differences, but
not sure what the issue is to be honest

On Thu, Nov 26, 2015 at 8:56 PM, Kevin Hughes <notifications@github.com>
wrote:

> Yeah webhooks created in the admin are not the same as those created by
> the app. The webhook_session block will filter invalid webhooks and then
> one you created in the admin will not be signed properly for the app so it
> will be invalid.
>
> Do you get the other webhook you created from install?
>
> I am also planning to update the install method. Rather than calling it
> install its really an after_auth callback and this callback can run
> anytime someone logs in. This is easier than trying to keep track of the
> installed state. The new install will need to be idempotent (i.e. running
> it twice is the same as running it once). Have a look at shopify_app and
> the new webhooks manager to see what it will be like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinhughes27/shopify-sinatra-app/issues/11#issuecomment-159993221>
> .
>



-- 
Toby Green

**Comment by kevinhughes27** [comment]
If you guery in the app for all your webhooks can you see the hook? Make sure it got created. I am going to close this issue though since I have an app using this framework with webhooks and webhook creation isn't part of the framework.

**Comment by tobeee** [comment]
Is there a solid way to check if the webhooks have been created? Is there
something I can query in the API perhaps?

On Fri, Nov 27, 2015 at 3:08 PM, Kevin Hughes <notifications@github.com>
wrote:

> If you guery in the app for all your webhooks can you see the hook? Make
> sure it got created. I am going to close this issue though since I have an
> app using this framework with webhooks and webhook creation isn't part of
> the framework.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinhughes27/shopify-sinatra-app/issues/11#issuecomment-160156884>
> .
>



-- 
Toby Green

**Comment by kevinhughes27** [comment]
Yeah you can get all your webhooks by doing `Webhooks.all` just like any other Shopify resource. I usually change the example products index page to show webhooks

**Comment by tobeee** [comment]
Will take a look - thanks as always Kevin

On Fri, Nov 27, 2015 at 3:10 PM, Kevin Hughes <notifications@github.com>
wrote:

> Yeah you can get all your webhooks by doing Webhooks.all just like any
> other Shopify resource. I usually change the example products index page to
> show webhooks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinhughes27/shopify-sinatra-app/issues/11#issuecomment-160157242>
> .
>



-- 
Toby Green

**Comment by skillmatic-co** [comment]
@kevinhughes27 Is a migration missing for these webhooks? I think out of the box, uncommenting everything in `after_shopify_auth` doesn't work, I'm getting an `ActiveResource::ResourceInvalid` error on `uninstall_webhook.save!`.

**Comment by kevinhughes27** [comment]
did you run the migrations to create the shop table? The framework does handle saving a shop record for you automatically.

**Comment by skillmatic-co** [comment]
> did you run the migrations to create the shop table? The framework does handle saving a shop record for you automatically.

@kevinhughes27 Yes. Actually figuring out that `uninstall_webhook.save!` doesn't save anything locally, but saves it with Shopify. I think there's an issue with this `save!` method somewhere, doing reading here to see if related: https://github.com/rails/activeresource/issues/309

**Comment by skillmatic-co** [comment]
Here's my stack trace:

```
2019-04-26 12:00:02 - ActiveResource::ResourceInvalid - Failed.:
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/activeresource-5.1.0/lib/active_resource/base.rb:1349:in `save!'
	/Users/foo/www/sites/test-sinatra-app/src/app.rb:77:in `block in after_shopify_auth'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/shopify-sinatra-app-0.8.0/lib/sinatra/shopify-sinatra-app.rb:42:in `shopify_session'
	/Users/foo/www/sites/test-sinatra-app/src/app.rb:65:in `after_shopify_auth'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/shopify-sinatra-app-0.8.0/lib/sinatra/shopify-sinatra-app.rb:232:in `block in registered'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:420:in `call_app!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:373:in `callback_phase'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-shopify-oauth2-2.1.0/lib/omniauth/strategies/shopify.rb:128:in `callback_phase'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:238:in `callback_call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:189:in `call!'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
	/Users/foo/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	/Users/foo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
	/Users/foo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
	/Users/foo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by kevinhughes27** [comment]
I'd try and get a debugger inline after the save call and see what the full response from Shopify is.

**Comment by skillmatic-co** [comment]
@kevinhughes27 if I put byebug in after the save call, the error has already occurred and doesn't let me debug with byebug. If I put byebug before the save call, and I try to manually call `uninstall_webhook.save!` I get:

```
(byebug) uninstall_webhook.save!
*** ActiveResource::ResourceInvalid Exception: Failed.

nil
(byebug) 
```

**Comment by kevinhughes27** [comment]
Can you inspect the webhook object? you could also just use `save` if that is easier. Shopify API stores the errors on that object.

**Comment by skillmatic-co** [comment]
@kevinhughes27 Getting somewhere...

```
(byebug) uninstall_webhook
#<ShopifyAPI::Webhook:0x00007ff4640ad538 @attributes={"topic"=>"app/uninstalled", "address"=>"https://df4f3ed0.ngrok.io/uninstall", "format"=>"json"}, @prefix_options={}, @persisted=false, @remote_errors=#<ActiveResource::ResourceInvalid: Failed.  Response code = 422.  Response message = Unprocessable Entity.>, @validation_context=nil, @errors=#<ActiveResource::Errors:0x00007ff464f112a0 @base=#<ShopifyAPI::Webhook:0x00007ff4640ad538 ...>, @messages={:address=>["for this topic has already been taken"]}, @details={:address=>[{:error=>"for this topic has already been taken"}]}>>
(byebug) 
```

**Comment by skillmatic-co** [comment]
So it looks like the webhook has already been created, will figure out a better to way to check if it exists first before saving.

**Comment by kevinhughes27** [comment]
Sorry for being lazy and not checking myself but doesn't the framework rescue that error? If the hook already exists it should just rescue and carry on.

**Comment by skillmatic-co** [comment]
@kevinhughes27 It doesn't, I was getting a hard application ending error.

**Comment by kevinhughes27** [comment]
Ah right this is all left to you with this framework. I would add a rescue inside the after_install method and catch this. For reference this is how I do it in my app https://github.com/kevinhughes27/shopify-tax-receipts/blob/master/src/jobs/after_install_job.rb and the ShopifyApp rails engine does similar

**Comment by skillmatic-co** [comment]
@kevinhughes27 Thanks!
