### ISSUE TITLE
shopify-sinatra-app-generator specifies path to shopify-sinatra-app as '../'

### ISSUE THREAD

**Issue by lrettig** [kevinhughes27/shopify-sinatra-app#18]
The `Gemfile` for a newly-generated app contains the line:

`gem 'shopify-sinatra-app', path: '../'`

 (see e.g. https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/example/Gemfile#L4).

Whenever I try to `bundle install` for this app, I get an error:

```
> bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Could not find gem 'shopify-sinatra-app' in source at `..`.
Source does not contain any versions of 'shopify-sinatra-app'
```

It seems like the path should not be `../` for any app but the included example app. Indeed, after removing the `path` spec the bundle command works. Am I missing something?

Thank you

**Comment by kevinhughes27** [comment]
Hmm the generator used to be aware about how to change that line: https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/bin/shopify-sinatra-app-generator#L48

Maybe it isn't working anymore.

**Comment by kevinhughes27** [comment]
Fixed! Thanks for opening an issue :)
