### ISSUE TITLE
Overriding Shop class

### ISSUE THREAD

**Issue by lrettig** [kevinhughes27/shopify-sinatra-app#20]
If I want to use a different data backing for Shop data, i.e., not ActiveRecord, it seems to make sense to override the Shop class. Is this a reasonable course of action? How would you recommend doing this?

(I want to use a NoSQL datastore, and to merge this data with an existing Shop data table.)

Thank you.

**Comment by kevinhughes27** [comment]
Yup that could probably work! If you were ambitious you could refactor the shop class to use a repository pattern to abstract the datastore away from the framework and submit a PR :)

This is how we do it in our Rails framework https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/shopify_session_repository.rb

**Comment by lrettig** [comment]
Sounds good, thanks for the tip. I'll give it some thought and come back if I have more questions.
