### ISSUE TITLE
logout doesn't work properly

### ISSUE THREAD

**Issue by lrettig** [kevinhughes27/shopify-sinatra-app#21]
If you [`logout`](https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/lib/sinatra/shopify-sinatra-app.rb#L22) and then attempt to load an endpoint that runs inside [`shopify_session`](https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/lib/sinatra/shopify-sinatra-app.rb#L42) you get a crash with `NoMethodError: undefined method '[]' for nil:NilClass`.

This happens because `logout` clears the value of `session[:shopify]` but leaves the key present:

```
        session[:shopify] = nil
```

Then `shopify_session` checks for the existence of the key (it still exists):

```
        if !session.key?(:shopify)
```

and then tries to read a key below this key

```
        else
          shop_name = session[:shopify][:shop]
          token = session[:shopify][:token]
```

The issue is demonstrated by this unit test:

```
  def test_broken_logout
    set_session
    SinatraApp.any_instance.expects(:verify_shopify_webhook).returns(true)
    Shop.any_instance.expects(:destroy)

    post '/uninstall', '{}', 'HTTP_X_SHOPIFY_SHOP_DOMAIN' => @shop_name

    assert last_response.ok?

    assert_raises NoMethodError do
      get '/'
    end
  end
```

Let me know if I'm missing something, otherwise I'm happy to PR. Thanks.

**Comment by kevinhughes27** [comment]
Looks like a legit bug to me! Nice find :)
