### ISSUE TITLE
Page Does Not Exist

### ISSUE THREAD

**Issue by FLWallace105** [kevinhughes27/shopify-sinatra-app#23]
Hi, when I try something like this setup:

app url: https://6d4d8551.ngrok.io/ 
redirect url: http://localhost:4567/auth/shopify/callback 
No Embedded App, I get the following error:  Not Found: The page you were looking for does not exist.

However, the Sinatra Logs look like this:

WARN: tilt autoloading 'tilt/erb' in a non thread-safe way; explicit require 'tilt/erb' suggested.
::1 - - [01/Jun/2017:17:35:08 -0700] "POST /login HTTP/1.1" 200 1095 0.0192
I, [2017-06-01T17:35:08.599158 #1930]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2017-06-01T17:35:08.599335 #1930]  INFO -- omniauth: (shopify) Request phase initiated.
::1 - - [01/Jun/2017:17:35:08 -0700] "GET /auth/shopify?shop=myshopnameredacted.myshopify.com&return_to=http://localhost:4567/ HTTP/1.1" 302 296 0.0068
I, [2017-06-01T17:35:08.850136 #1930]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2017-06-01T17:35:08.850402 #1930]  INFO -- omniauth: (shopify) Callback phase initiated.
D, [2017-06-01T17:35:09.121693 #1930] DEBUG -- :   Shop Load (0.5ms)  SELECT  "shops".* FROM "shops"  WHERE "shops"."name" = 'myshopnameredacted.myshopify.com' LIMIT 1
D, [2017-06-01T17:35:09.126007 #1930] DEBUG -- :    (0.2ms)  BEGIN
D, [2017-06-01T17:35:09.126432 #1930] DEBUG -- :    (0.1ms)  COMMIT
::1 - - [01/Jun/2017:17:35:09 -0700] "GET /auth/shopify/callback?code=<<redacted>>&hmac=<redacted>&shop=myshopnameredacted.myshopify.com&state=<redacted>&timestamp=1496363708 HTTP/1.1" 302 - 0.2793
::1 - - [01/Jun/2017:17:35:09 -0700] "GET / HTTP/1.1" 200 2196 0.2705

FWIW I am using Puma instead of Webbrick or Thin.

Thanks! I so want to get this working! Gem looks awesome.

**Comment by kevinhughes27** [comment]
Can you try using the ngrok url for the redirect as well? (with the /auth ... etc still)

**Comment by FLWallace105** [comment]
Hey Kevin — thanks, I got the app to load completely by making it an embedded app. Funny huh?

I’d like to help contribute to your excellent gem, it rocks btw and for a lot of Shopify stuff, Sinatra is nice and light and easier than the Rails gem if all you are doing is proxying or web hooks and such with Redis/Resque.

For some reason I can’t get my private app proxy to work on production, it works fine on my test/development store. Not even with the Classy Sinatra App sigh.

Has anyone on your team run into that before? Shopify seems to nuke behind the scenes all the proxy requests. Weird.

Have a great weekend!

Floyd Wallace
Developer
FAM Brands LLC

**Comment by kevinhughes27** [comment]
Oh my bad I didn't realise you're app wasn't embedded when you first posted. This gem only works with embedded apps due to this code in the layout https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/example/views/layouts/application.erb#L4-L11. You could remove it if you want but the auth flow is also built for embedded apps (using JS to redirect) and embedded apps are preferred by Shopify.

I'm not super familiar with private app proxies so you might be better off contacting Shopify developer support.
