### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by AdityaAnand1** [kevinhughes27/shopify-sinatra-app#29]
Pardon me, I'm new to the whole ruby environment. I've been following the instructions in the [shopify docs](https://help.shopify.com/api/tutorials/building-public-app) and trying to get this repo to work with ngrok.

In the README, it states:

> To run the app locally we use foreman which comes with the Heroku Toolbelt. Foreman handles running our application and setting our credentials as environment variables. To run the application type:

> foreman run bundle exec rackup config.ru

When I execute the above, I get the following error:

```C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/foreman-0.78.0/lib/foreman/cli.rb:86:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/foreman-0.78.0/lib/foreman/cli.rb:86:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/foreman-0.78.0/bin/foreman:7:in `<top (required)>'
        from C:/Ruby23-x64/bin/foreman:23:in `load'
        from C:/Ruby23-x64/bin/foreman:23:in `<main>'```

I know that this is a long standing issue effecting a lot of gems > the fork() method is not implemented for Windows.

So my point is, how do I run this app locally on windows?

I tried the following (given that this is how it works in the [official docs](https://help.shopify.com/api/tutorials/building-public-app)): 

```ruby lib/app.rb```

And then I get the error:

```C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `require': Could not load 'active_record/connection_adapters/sqlite3_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)```

Which I'm not sure what it means. I tried changing the production gem in the GEMFILE to sqlite3 too, but it didn't do anything. I've confirmed that I have the sqlite3 gem installed. I'm not sure what else to do, does using a database requite any other kind of setup?

**Comment by kevinhughes27** [comment]
Foreman is a utility for running multiple processes, these processes are defined in the `Procfile`. If you open this file you'll see the command for each process. 

https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/example/Procfile#L1

I think the issue with your `ruby lib/app.rb` command is that you are not invoking bundler. Bundler ensures you have access to all the dependencies you've defined in the Gemfile.
