### ISSUE TITLE
Updating ShopifyAPI

### ISSUE THREAD

**Issue by pliew** [kevinhughes27/shopify-sinatra-app#31]
I notice that the ShopifyAPI version is quite old and doesn't include the Refund object.  How would you go about updating the gem?

**Comment by kevinhughes27** [comment]
The version is specified in the gemspec file here: https://github.com/kevinhughes27/shopify-sinatra-app/blob/master/shopify-sinatra-app.gemspec#L25.

It should definitely be updated - can you submit a PR?
