### ISSUE TITLE
The shop record in the shops table is not deleted after uninstalling the app.

### ISSUE THREAD

**Issue by petergu** [kevinhughes27/shopify-sinatra-app#35]
After uninstalling the app, I can still see the shop record in the shops table.

**Comment by kevinhughes27** [comment]
Did the app receive the webhook? If you're running it locally you'll need to use a tunneling service like ngrok and route the webhook through the tunnel in order to have this work. Production should work without extra setup.

**Comment by petergu** [comment]
Thanks Kevin. 
I just created an app by using the generator and pushed it to Heroku.  It worked, then I uninstalled the app, I checked the shops table by using "heroku pg:psql", I still saw  my test shop record there.

**Comment by kevinhughes27** [comment]
Can you check the heroku logs to see if the webhook was received? That will help narrow down where the problem is.

**Comment by petergu** [comment]
NVM, I need to uncomment out the codes in the "after_shopify_auth" method. Now it works. 
Any reason that those codes generated by the generator are commented out?

**Comment by kevinhughes27** [comment]
I'm not sure either. It seems inconsistent to have the code for the uninstall endpoint but not register the webhook.
