### ISSUE TITLE
Unable to install app running locally using ngrok

### ISSUE THREAD

**Issue by njdehoog** [kevinhughes27/shopify-sinatra-app#50]
This project seems like a great start for my Shopify plugin. Unfortunately I am unable to install the app on a live store while running it locally though.

I've set everything up using ngrok, like described in the README, but when I try to install the app in my test store I get the following error message:

`Oauth error invalid_request: The redirect_uri is not whitelisted`

The redirect url seems to be the ngrok url rather than the localhost url I've configured in Shopify.

I've tried a bunch of different things, but I can't make it work. Any help would be appreciated.

**Comment by kevinhughes27** [comment]
It sounds like you need to configure the ngrok url in Shopify.

**Comment by njdehoog** [comment]
Good point. I had tried that before, but had somehow not realized that I was using the http rather than the https url.

It works now using the ngrok url as the redirect_uri. Perhaps it would be worth updating the README?

**Comment by kevinhughes27** [comment]
Great idea! https://github.com/kevinhughes27/shopify-sinatra-app/commit/0d0893639f4aa5b4256c7086ef52cec1a8038d5f

If you think the readme needs more tweaking go for it and open a PR!
