### ISSUE TITLE
Heroku Setup

### ISSUE THREAD

**Issue by tobeee** [kevinhughes27/shopify-sinatra-app#8]
Hi there,

This looks super interesting! Having some issues getting it all set up with Heroku. It seems like there was a step missing, as the database.yml needs to be modified slightly for the rake db:Create command to work on Heroku.

I needed to add:

production:
  url: <%= ENV['DATABASE_URL'] %>
  
<edit>

However, now it's all up and running I seem to run in the issues laid out in this post - https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/problem-with-embedded-sdk-not-loading-the-iframe-275604

I think it might be because the Gemfile has a very old version of the Shopify gem? I've tried manually adjusting the URL but it's been a bit tricky...anyone else managed to get this up and running?

**Comment by kevinhughes27** [comment]
Hey! thanks for the bug report, I had to do something similar in my main app that is using this framework (you can check the source here https://github.com/kevinhughes27/shopify-tax-receipts). If you'd like to submit the change as a PR I'll gladly accept it.

As for your auth issues I'm not too sure what could be going on. One thing it could be is that new apps require a `redirect_uri` to be whitelisted and sent in the auth request (have a look at the most recent commits to https://github.com/Shopify/shopify_app a rails framework). I'm on vacation so I won't be able to look at this for a bit. If you figure anything please post here or submit a PR!

**Comment by tobeee** [comment]
Hi Kevin,

Will submit a PR for the first bit at some point.

With regards to the auth issues - I've spent a few hours trying to work out what's going on, but there is something really fishy going on. While the Rails example had a few examples, I can't seem to work out how on earth the Sinatra extension builds the URLs, so it keeps sending shopify malformed data which causes it not to work :(

If you get a chance to look at it at some point that would be awesome - bet it's something simple!

**Comment by tobeee** [comment]
Think I've narrowed it down to a couple of issues. I've managed to get it working by manually fixing the redirect URI.

Currently it redirects to the following: 
https://chescatesting.myshopify.com/admin/oauth/authorize?client_id=redacted&redirect_uri=http%3A%2F%2Fblahshopify.herokuapp.com%2Fauth%2Fshopify%2Fcallback%3Fshop%3Dblahtesting.myshopify.com%26return_to%3Dhttps%3A%2F%2Fblahshopify.herokuapp.com%2F&response_type=code&scope=read_products%2C+read_orders%2C+write_orders&state=redacted

Note a number of issues:

i) Redirect URI has HTTP in it, instead of HTTPS -> This could then easily be amended in the Shopify app settings, so not the end of the world
ii) Note that URL string is escaped, not sure if that makes a difference to Shopify, but obviously the URLs won't match
iii) The Sinatra module seems to append an extra query string to the redirect_uri - namely ?shop=shopname, which again won't match with the redirect url in the Shopify app settings

To *brute force install* the app, which will only work if you own the shop too, the method I've done is as follows:

i) Unescape the complete URL
ii) Strip the return_uri to match the one in your shopify settings completey 
iii) Go to the link manually

I guess the AuthToken might not last forever, so I assume this will have to be done periodically....quite annoying!

**Comment by kevinhughes27** [comment]
If you set the callback url param in omniauth like we do in shopify app it
won't send the shop param.

**Comment by tobeee** [comment]
Thanks Kevin

Not 100% sure where to set it inside the app though?

On Sat, Nov 14, 2015 at 11:10 AM, Kevin Hughes <notifications@github.com>
wrote:

> If you set the callback url param in omniauth like we do in shopify app it
> won't send the shop param.
> On Nov 14, 2015 5:22 AM, "tobeee" <notifications@github.com> wrote:
>
> > Think I've narrowed it down to a couple of issues. I've managed to get it
> > working by manually fixing the redirect URI.
> >
> > Currently it redirects to the following:
> >
> >
> https://chescatesting.myshopify.com/admin/oauth/authorize?client_id=redacted&redirect_uri=http%3A%2F%2Fblahshopify.herokuapp.com%2Fauth%2Fshopify%2Fcallback%3Fshop%3Dblahtesting.myshopify.com%26return_to%3Dhttps%3A%2F%2Fblahshopify.herokuapp.com%2F&response_type=code&scope=read_products%2C+read_orders%2C+write_orders&state=redacted
> >
> > Note a number of issues:
> >
> > i) Redirect URI has HTTP in it, instead of HTTPS -> This could then
> easily
> > be amended in the Shopify app settings, so not the end of the world
> > ii) Note that URL string is escaped, not sure if that makes a difference
> > to Shopify, but obviously the URLs won't match
> > iii) The Sinatra module seems to append an extra query string to the
> > redirect_uri - namely ?shop=shopname, which again won't match with the
> > redirect url in the Shopify app settings
> >
> > To *brute force install* the app, which will only work if you own the
> > shop too, the method I've done is as follows:
> >
> > i) Unescape the complete URL
> > ii) Strip the return_uri to match the one in your shopify settings
> > completey
> > iii) Go to the link manually
> >
> > I guess the AuthToken might not last forever, so I assume this will have
> > to be done periodically....quite annoying!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156681329
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156687225>
> .
>



-- 
Toby Green

**Comment by kevinhughes27** [comment]
It will be where the omniauth stuff is configured. That's all I have for
now sorry. I'll take a close look when I'm back from vacation in about a 2
weeks. In the meantime it sounds like you got it installed so you should be
able to develop.

**Comment by tobeee** [comment]
Yup all good for now. Will let you know if I manage to fix it

Thanks for the help so far. Enjoy the rest of your vacation!

On Sat, Nov 14, 2015 at 11:16 AM, Kevin Hughes <notifications@github.com>
wrote:

> It will be where the omniauth stuff is configured. That's all I have for
> now sorry. I'll take a close look when I'm back from vacation in about a 2
> weeks. In the meantime it sounds like you got it installed so you should be
> able to develop.
>
> On Nov 14, 2015 6:12 AM, "tobeee" <notifications@github.com> wrote:
>
> > Thanks Kevin
> >
> > Not 100% sure where to set it inside the app though?
> >
> > On Sat, Nov 14, 2015 at 11:10 AM, Kevin Hughes <notifications@github.com
> >
> > wrote:
> >
> > > If you set the callback url param in omniauth like we do in shopify app
> > it
> > > won't send the shop param.
> > > On Nov 14, 2015 5:22 AM, "tobeee" <notifications@github.com> wrote:
> > >
> > > > Think I've narrowed it down to a couple of issues. I've managed to
> get
> > it
> > > > working by manually fixing the redirect URI.
> > > >
> > > > Currently it redirects to the following:
> > > >
> > > >
> > >
> >
> https://chescatesting.myshopify.com/admin/oauth/authorize?client_id=redacted&redirect_uri=http%3A%2F%2Fblahshopify.herokuapp.com%2Fauth%2Fshopify%2Fcallback%3Fshop%3Dblahtesting.myshopify.com%26return_to%3Dhttps%3A%2F%2Fblahshopify.herokuapp.com%2F&response_type=code&scope=read_products%2C+read_orders%2C+write_orders&state=redacted
> > > >
> > > > Note a number of issues:
> > > >
> > > > i) Redirect URI has HTTP in it, instead of HTTPS -> This could then
> > > easily
> > > > be amended in the Shopify app settings, so not the end of the world
> > > > ii) Note that URL string is escaped, not sure if that makes a
> > difference
> > > > to Shopify, but obviously the URLs won't match
> > > > iii) The Sinatra module seems to append an extra query string to the
> > > > redirect_uri - namely ?shop=shopname, which again won't match with
> the
> > > > redirect url in the Shopify app settings
> > > >
> > > > To *brute force install* the app, which will only work if you own the
> > > > shop too, the method I've done is as follows:
> > > >
> > > > i) Unescape the complete URL
> > > > ii) Strip the return_uri to match the one in your shopify settings
> > > > completey
> > > > iii) Go to the link manually
> > > >
> > > > I guess the AuthToken might not last forever, so I assume this will
> > have
> > > > to be done periodically....quite annoying!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156681329
> > > >
> > > > .
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156687225
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Toby Green
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156687259
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinhughes27/shopify-sinatra-app/issues/8#issuecomment-156687414>
> .
>



-- 
Toby Green
